<?php
/**
 * Implementation of hook_menu
 */
 function create_xml(){
    $dom = new DOMDocument('1.0','utf-8'); 
    $element = $dom->createElement('markers');
    $parnode = $dom->appendChild($element);
	$table = 'osmap';
	$osmap_true = 1;
    
    $query = ('SELECT * FROM '. $table. ' WHERE ' . $osmap_true);
    $result = db_query($query);
	
    if (!$result) {  
       die('Invalid query: ' . mysql_error());
     }     
// Iterate through the rows, adding XML nodes for each
     while ($row=$result->fetchAssoc()){
        $element = $dom->createElement('marker');
         $newnode = $parnode->appendChild($element);
	     $newnode->setAttribute('name',$row['name']);
         $newnode->setAttribute('address', $row['address']);
         $newnode->setAttribute('lat', $row['lat']);
         $newnode->setAttribute('lng', $row['lng']);
         $newnode->setAttribute('type', $row['type']);
		 $newnode->setAttribute('title', $row['title']);
	    }
	
	$strxml = $dom->saveXML();
    return $strxml;
	}
function sample_map_menu(){
	
    $items = array();
    $items['sample_map'] = array(
        'title' => 'sample map example',
        'description' => 'A simple module changes the html context using JavaScript',
        'page callback' => 'sample_map_show', // call the page
		'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access content'), //The argument below is recommended for all users to have access to a page.
    );		
	$items['sample_map/xml'] = array(
        'title' => 'XML',
        'page callback' => 'sample_map_xml',
	    'access callback' => TRUE,
	    'type' => MENU_NORMAL_ITEM,
  ); 
	 return $items;
}

function sample_map_show(){
	$build = array(
	  '#markup' => '<div id="googleMap" style="width:500px;height:380px;"></div>',
	  '#attached' => array (
	     'js' => array (
		    'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false' => array('type' => 'external',),
	        drupal_get_path('module', 'sample_map') . '/sample_map.js' ,
	    ),
	  ),
     );
		 
    return $build;	  
}

function sample_map_xml() {
   drupal_add_http_header('Content-Type', 'application/xml; charset=utf-8');
   $map_xml = create_xml();
   echo $map_xml;
   exit();
}








