<?php
/**
 * Created by PhpStorm.
 * User: King
 * Date: 14-2-4
 * Time: 下午12:38
 */

/**
 * Implementation of hook_menu
 */
function map_example_menu(){

	
    $items = array();
    $items['map_example'] = array(
        'title' => 'map_example',
        'description' => 'A simple module changes the html context using JavaScript',
        'page callback' => 'map_show', // call the page
		'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access content'), //The argument below is recommended for all users to have access to a page.
    );
		
    return $items;
}

function map_show(){

	drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyAz4kiKnyoMKp0e8ORuqbWNZZpplrxGsGE&sensor=true', 'external');
	drupal_add_js('sites/all/modules/map_example/source.js');
	
	return '<div id="googleMap" style="width:500px;height:380px;"></div>';
			
}











