<?php  

/**
 * @file
 * osmap module implementing simple hook_menu
 */
  
function ajaxtest_menu() {
  $items = array();

  $items['ajax-test'] = array(
    'title' => 'Ajax Test',
	'page callback' => 'ajax_link_page',
   	'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access content'),
  );
  
  $items['my-ajax-test/%'] = array(
   'title' => 'Ajax test callback',
   'type' => MENU_CALLBACK,
   'page callback' =>'ajax_link_callback',
   'page arguments' => array(1),  
   'access arguments' => array('access content'),
  );
  return $items;
}
 
 function ajax_link_page(){
   return array(
    '#type' => 'link',
	'#title' => t('Ajax Link'),
	'#href' => 'my-ajax-test/nojs',
	'#prefix' =>'<div id="ajax-link">',
	'#suffix' =>'</div><div id="ajax-display">Hello</div>',
	'#ajax' => array('effect' => 'fade',),  
   ); 
 }
 
 
 function ajax_link_callback($ajax){
     $ajax_thx = t('!ajax_thx', array('!ajax_thx' => 'thank you'));
   if($ajax == 'ajax'){
     $commands = array();
     $commands[] = ajax_command_replace('#ajax-display', $ajax_thx . "</div>");
	// $commands[] = ajax_command_changed('#ajax-display');
	 ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
	 };
 }
