<?php
/**
 * @file
 * osmap module implementing simple hook_menu
 */
/**
 * Implements hook_menu().
 *
 * Set up calls to drupal_get_form() for all our example cases.
 */
/**function dbtng_example_menu() {*/
function osmap_menu(){

  $items = array();

  $items['example/osmap'] = array(
    'title' => 'OSMAP Example',
    'page callback' => 'osmap_example',
    'access callback' => TRUE,
  );
  
  return $items;
}

/**
 * Render a list of entries in the database.
 */
function osmap_example() {
  return '<div id="map" style="width: 500px; height: 300px"></div>';
}

